runtime.conversion.handler = none
parser.space_gobbling = bc
directive.if.empty_check = false
resource.loaders=file,class
resource.loader.file.path=/data/solr-run/data/OntoMate/conf/velocity
resource.loader.file.class=org.apache.velocity.runtime.resource.loader.FileResourceLoader
resource.loader.class.class=org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
resource.loader.import.enabled=true
pwd