runtime.conversion.handler = none
space.gobbling = bc
directive.if.emptycheck = false
resource.loader=file,class
file.resource.loader.path=/data/solr-run/data/OntoMate/conf/velocity
file.resource.loader.class=org.apache.velocity.runtime.resource.loader.FileResourceLoader
class.resource.loader.class=org.apache.velocity.runtime.resource.loader.ClasspathResourceLoader
import.resource.loader.enabled=true